name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
    - name: checkout-code
      uses: actions/checkout@v4

    - name: set-up-go
      uses: actions/setup-go@v5

    - name: install-deps
      run: make deps

    - name: make-scripts-executable
      run: chmod +x ./scripts/get_version.sh ./scripts/check_tag_exists.sh ./scripts/build.sh

    - name: get-version
      run: ./scripts/get_version.sh

    - name: check-tag-exists
      run: ./scripts/check_tag_exists.sh

    - name: build-all
      run: make

    - name: release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            lenv-linux-amd64
            lenv-linux-arm64
            lenv-windows-amd64.exe
            LICENSE
