name: ci

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64

    steps:
    - name: checkout-code
      uses: actions/checkout@v4

    - name: set-up-go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: install-deps
      run: make deps

    - name: test
      run: go test
